# Generated by Django 3.2.13 on 2022-05-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0006_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
