# Generated by Django 3.2.13 on 2022-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0010_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='images/'),
        ),
    ]
