# Generated by Django 3.2.13 on 2022-05-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0012_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
