# Generated by Django 3.2.13 on 2022-06-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0020_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
