# Generated by Django 3.2.13 on 2022-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0023_rename_title_imagss_title_im'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagss',
            name='title_im',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
