# Generated by Django 3.2.13 on 2022-06-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0025_rename_image_imagss_image_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagss',
            name='title_im',
        ),
    ]
