# Generated by Django 3.2.13 on 2022-08-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0030_auto_20220812_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name1',
        ),
    ]
