# Generated by Django 3.2.13 on 2022-08-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0031_auto_20220812_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
