# Generated by Django 3.2.13 on 2023-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0036_commentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpro',
            name='status',
            field=models.CharField(choices=[('New', 'Mới'), ('True', 'Hiện'), ('False', 'Ẩn')], default='New', max_length=10),
        ),
    ]
