# Generated by Django 3.2.13 on 2023-07-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0038_auto_20230708_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('ordinal_numbers', models.IntegerField(blank=True)),
                ('videos', models.FileField(blank=True, upload_to='videos/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_index.product')),
            ],
        ),
    ]
