# Generated by Django 3.2.13 on 2023-07-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0040_video_list_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='couse_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_index.product')),
            ],
        ),
    ]
