# Generated by Django 3.2.13 on 2023-07-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0041_couse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='couse_title',
            name='ordinal_numbers',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name='cource_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('ordinal_numbers', models.IntegerField(blank=True)),
                ('videos', models.FileField(blank=True, upload_to='videos/')),
                ('pdffile', models.FileField(blank=True, upload_to='filepdf/')),
                ('cource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_index.couse_title')),
            ],
        ),
    ]
