# Generated by Django 3.2.13 on 2023-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0042_auto_20230717_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource_video',
            name='titlevideo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
