# Generated by Django 3.2.13 on 2023-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_commentblog_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
