# Generated by Django 3.2.13 on 2023-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_commentblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
