# Generated by Django 3.2.13 on 2023-08-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, max_length=255)),
                ('Email', models.CharField(blank=True, max_length=255)),
                ('Phone', models.CharField(blank=True, max_length=255)),
                ('Note', models.TextField(blank=True)),
            ],
        ),
    ]
