# Generated by Django 3.2.13 on 2023-05-29 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_index', '0037_alter_commentpro_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=15)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Phone', models.CharField(blank=True, max_length=200)),
                ('Mail', models.CharField(blank=True, max_length=200)),
                ('Address', models.CharField(blank=True, max_length=225)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Processing', 'Đang xử lý'), ('Pending_payment', 'Chờ thanh toán'), ('Completed', 'Đã hoàng thành'), ('On_hold', 'Tạm giữ'), ('Cancelled', 'Đã hủy'), ('Refunded', 'Đã hoàng lại tiền'), ('Failed', 'Đơn hàng thất bại'), ('Draft', 'Draft')], default='Processing', max_length=15)),
                ('total', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTotalInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_index.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
