# Generated by Django 3.2.13 on 2023-06-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_producttotalincart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttotalincart',
            name='user',
        ),
    ]
